services:
  UBOS\Theme\EventListener\AdditionalPropertiesForSearchAction:
    tags:
      - name: event.listener
        identifier: 'myAdditionalPropertiesForSearchAction'
        event: Brotkrueml\Schema\Event\RegisterAdditionalTypePropertiesEvent