name: ubos/puck
label: Puck site package
dependencies:
  - typo3/fluid-styled-content
  - typo3/redirects
  - typo3/seo-sitemap
settings:
  doktypes:
    news: 16503
    person: 16504
    detailPlugin: 16511
  template:
    gridWidth: 1280
