categories:
  Puck:
    label: Puck site package
  Puck.system:
    label: System
    parent: Puck
  Puck.template:
    label: Template
    parent: Puck

settings:
  template.rootLayout:
    label: Root layout
    description: 'Base layout type for site'
    category: Puck.template
    type: string
    default: default
    enum:
      default: 'Default'
  template.logo:
    label: Logo
    category: Puck.template
    type: string
    default: default
    enum:
      default: 'Default'
  template.favicon:
    label: Favicon
    category: Puck.template
    type: string
    default: default
    enum:
      default: 'Default'
  system.enableCookieSettings:
    label: Enable cookie settings
    description: Show cookie settings link in footer
    category: Puck.system
    type: bool
    default: false
  system.searchPageUid:
    label: Search page
    description: Uid of search plugin page
    category: Puck.system
    type: string
    default: ''