categories:
  Puck:
    label: Puck site package

settings:
  puck.enableCookieSettings:
    label: Enable cookie settings
    description: Show cookie settings link in footer
    category: Puck
    type: bool
    default: false
  puck.searchPageUid:
    label: Search page
    description: Uid of search plugin page
    category: Puck
    type: string
    default: ''
  puck.rootLayout:
    label: Root layout
    description: 'Base layout type for site'
    category: Puck
    type: string
    default: default
    enum:
      default: 'Default'
  puck.logo:
    label: Logo
    category: Puck
    type: string
    default: default
    enum:
      default: 'Default'
  puck.favicon:
    label: Favicon
    category: Puck
    type: string
    default: default
    enum:
      default: 'Default'