<?php

return [
	'label' => 'label',
	'title' => 'Form field',
	'tstamp' => 'tstamp',
	'crdate' => 'crdate',
	'origUid' => 't3_origuid',
	'sortby' => 'sorting',
	'delete' => 'deleted',
	'versioningWS' => true,
	'languageField' => 'sys_language_uid',
	'transOrigPointerField' => 'l10n_parent',
	'transOrigDiffSourceField' => 'l10n_diffsource',
	'iconfile' => 'EXT:puck/Resources/Public/Icons/Backend/Default.svg',
	'enablecolumns' => [
		'disabled' => 'hidden',
	],
	'searchFields' => 'label',
	'type' => 'type',
	'typeicon_column' => 'type',
	'typeicon_classes' => [
		'text' => 'form-text',
		'textarea' => 'form-textarea',
		'select' => 'form-single-select',
		'checkbox' => 'form-checkbox',
		'multi-checkbox' => 'form-multi-checkbox',
		'radio' => 'form-radio-button',
		'email' => 'form-email',
		'number' => 'form-number',
		'tel' => 'form-telephone',
		'password' => 'form-password',
		'url' => 'form-url',
		'color' => 'default',
		'range' => 'form-text',
		'date' => 'form-date-picker',
		'datetime-local' => 'form-date-picker',
		'time' => 'form-date-picker',
		'week' => 'form-date-picker',
		'month' => 'form-date-picker',
		'file' => 'form-file-upload',
		'reset' => 'default',
		'captcha' => 'default',
		'country' => 'default',
		'hidden' => 'form-hidden',
		'header' => 'form-static-text',
		'rte' => 'form-static-text',
		'content' => 'form-content-element',
		'repeatable-container' => 'default',
	],
];