name: ubos/puck
label: Puck site package
dependencies:
  - typo3/fluid-styled-content
  - typo3/redirects
  - typo3/seo-sitemap
  - amdeu/menu-controls
  - amdeu/shape
settings:
  puck:
    gridWidth: 1280
