# Load default processing options
imports:
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Processing.yaml" }
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml" }
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml" }

# Add configuration for the editor
# For complete documentation see http://docs.ckeditor.com/#!/api/CKEDITOR.config
editor:
  config:
    importModules:


    contentsCss:
      - 'EXT:puck/Resources/Public/Css/be-ck-contents.css'
      - 'EXT:rte_ckeditor/Resources/Public/Css/contents.css'

    style:
      definitions:

        #Headlines

        #Paragraphs
        - { name: "Small paragraph", element: "p", classes: [ "-small" ] }
        - { name: "Large paragraph", element: "p", classes: [ "-large" ] }
        - { name: "Footnote paragraph", element: "p", classes: [ "-footnote"] }
        - { name: "Quote paragraph", element: "p", classes: [ "-quote" ] }
        - { name: "Quote attribution paragraph", element: "p", classes: [ "-quote-attribution" ] }
        - { name: "Like h2 paragraph", element: "p", classes: [ "h2" ] }
        - { name: "Like h3 paragraph", element: "p", classes: [ "h3" ] }
        - { name: "Button group", element: "p", classes: [ "e-button-group" ] }
        - { name: "Button group without gutter", element: "p", classes: [ "-gutter-0 e-button-group" ] }

        # Headlines

        # link styles
        - { name: "Button", element: "a", classes: [ "e-button-primary"] }
        - { name: "Symbol button", element: "a", classes: [ "e-button-icon"] }
        - { name: "Button: full-width", element: "a", classes: [ '-block' ] }
        - { name: "Button: light", element: "a", classes: [ '-light' ] }
        - { name: "Button: outline", element: "a",classes: [ '-outline' ] }
        - { name: "Button: ghost", element: "a", classes: [ '-ghost' ] }
        - { name: "Button: icon left", element: "a", classes: [ '-icon', '-icon-left' ] }
        - { name: "Button: icon right", element: "a", classes: [ '-icon', '-icon-right' ] }
        - { name: "Button: icon framed", element: "a", classes: [ '-icon', '-icon-pill' ] }

        #Lists

        #List items

        # Tables
        - { name: "Row layout table", element: "table", classes: [ "row-layout-table"] }
        - { name: "Data table", element: "table", classes: ["data-table"] }

    heading:
      options:
        - { model: 'paragraph', title: 'Paragraph' }
        - { model: 'heading2', view: 'h2', title: 'Heading 2' }
        - { model: 'heading3', view: 'h3', title: 'Heading 3' }

    toolbar:
      items:
        - clipboard
        - removeFormat
        - undo
        - redo
        # grouping separator
        - '|'
        - find
        - selectAll
        - '|'
        - link
        - insertTable
        - tableColumn
        - tableRow
        - mergeTableCells
        - '|'
        - horizontalLine
        - bold
        - italic
        - underline
        - strikethrough
        - subscript
        - superscript
        - softhyphen
        - '|'
        - bulletedList
        - numberedList
        - blockQuote
        - indent
        - outdent
        - alignment
        - '|'
        - specialCharacters
        - Icons
        - '-'
        - style
        - heading
        - showBlocks
        - sourceEditing

    alignment:
      options:
        - { name: 'left', className: 'u-text-left' },
        - { name: 'center', className: 'u-text-center' }
        - { name: 'right', className: 'u-text-right' }
        - { name: 'justify', className: 'u-text-justify' }


    extraAllowedContent : "span(*); *(*)[data-*]; p[data-*]; a[data-*]; a span;"

    qtRows: 20
    qtColumns: 6

processing:
  allowTags:
    - wbr