base: /
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=7'
languages:
  -
    title: de
    enabled: true
    languageId: 0
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: de
    hreflang: de-DE
    direction: ltr
    flag: de
    websiteTitle: ''
  -
    title: en
    enabled: true
    base: /en/
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    websiteTitle: ''
    navigationTitle: en
    hreflang: en-US
    direction: ''
    fallbackType: free
    fallbacks: ''
    flag: en-us-gb
    languageId: 1
    xml_sitemap_path: /en/sitemap.xml
rootPageId: 2
settings:
  redirects:
    autoUpdateSlugs: true
    autoCreateRedirects: false
    redirectTTL: 0
    httpStatusCode: 307
websiteTitle: Puck
xml_sitemap_path: sitemap.xml
imports:
  -
    resource: 'EXT:puck/Configuration/Routes/Post.yaml'
  -
    resource: 'EXT:puck/Configuration/Routes/Person.yaml'
  -
    resource: 'EXT:puck/Configuration/Routes/Sitemap.yaml'
  -
    resource: 'EXT:puck/Configuration/Routes/TrailingSlash.yaml'
