services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  UBOS\Puck\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  UBOS\Puck\Preview\BasicPreviewRenderer:
    public: true
    arguments:
      $runtimeCache: '@cache.runtime'
  UBOS\Puck\Preview\PageMenuPreviewRenderer:
    public: true
    arguments:
      $runtimeCache: '@cache.runtime'