services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  UBOS\Puck\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  UBOS\Puck\EventListener\AdditionalPropertiesForSearchAction:
    tags:
      - name: event.listener
        identifier: 'puck-additional-schema-properties'

  UBOS\Puck\EventListener\ModifyRecordList:
    tags:
      - name: event.listener
        identifier: 'puck-record-list'

  UBOS\Puck\EventListener\ModifyNewContentElementWizard:
    tags:
      - name: event.listener
        # identifier is used to sort the listeners, needs to be before content_defender listener
        identifier: '01-puck-new-content-element-wizard'

  UBOS\Puck\EventListener\ModifyPageLayoutContent:
    tags:
      - name: event.listener
        identifier: 'puck-page-layout-content'